name: Lint Commit Messages

on:
  pull_request:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # 必须拉全历史
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.js   # 规则文件