name: Check Commit Messages
on: [pull_request, push]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check commits
        uses: wagoid/commitlint-github-action@v4